---
title: "Modelos Dinâmicos em Soft Commodities"
subtitle: "Financial Analytics"
institute: "Programa Avançado em Data Science - Insper"
author: "Luís Fechio, Viviane Sanchez"
date: "11/28/2020"
output: ioslides_presentation
#  xaringan::moon_reader:
#    lib_dir: libs
#    nature:
#      highlightStyle: github
#      highlightLines: true
#      countIncrementalSlides: false
#runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(RcppRoll)
library(bizdays)
library(derivmkts)

library(ggrepel)
library(highcharter)
library(shiny)
library(knitr)

library(timetk)

library(tidyverse)
library(tidyquant)
library(tidymodels)


load_rmetrics_calendars(2000:year(Sys.Date())+1)
#calendars()
bizdays.options$set(default.calendar='Rmetrics/NYSE')

theme_set(theme_minimal())
theme_update(text = element_text(family = "Open Sans"),
             plot.title = element_text(face = "bold", size = 23,
                                       color = "#1d3752"))
hc_cols <- c("#7cb5ec", "#434348", "#90ed7d", "#f7a35c", 
             "#8085e9", "#f15c80", "#e4d354", "#2b908f", 
             "#f45b5b", "#91e8e1")

options(digits=4)

quandl_api_key(Sys.getenv("QUANDL_TOKEN"))

#- como colocar o token no ambiente:
#
#abra o ambiente com o comando
#`usethis::edit_r_environ()`
#
# copie a linha abaixo com seu token
#
#QUANDL_TOKEN=(token)

```

## Introdução

Modelagem dinâmica dos preços das commodities softs listadas na [Intercontinental Exchange (ICE)](https://www.theice.com/products/Futures-Options/Agriculture)

- Açúcar VHP - `sugar`
- Cacau - `cocoa`
- Algodão - `cotton`
- Café - `coffee`
- Suco de laranja congelado - `orange_juice`


---
## Preços

```{r Read Prices}


cmdty_name <- c("sugar","cocoa","cotton","coffee", "orange_juice")

tickers <-  c("CHRIS/ICE_SB1", "CHRIS/ICE_CC1", 
              "CHRIS/ICE_CT1","CHRIS/ICE_KC1", 
              "CHRIS/ICE_OJ1")

cmdty_raw <- tq_get(tickers, get = "quandl", from = "2018-01-01", to  = Sys.Date()) %>% 
              #na.omit() %>% 
  left_join(tibble(cmdty = cmdty_name,
                   symbol = tickers), by = "symbol") %>% 
            group_by(symbol) %>% 
                   tq_mutate(select = settle,
                            mutate_fun = periodReturn,
                            period = "daily",
                            method = "log",
                            col_rename = "daily_return") %>% 
            mutate(acc_return = exp(cumsum(daily_return))-1,
                    sq_return = daily_return^2) %>% 
            ungroup()
  

#cmdty_raw %>% 
 # glimpse

```

---
## Série de preços

```{r Grafico1 - Prices}

cmdty_raw %>% 
    #mutate(daily_return = daily_return*100) %>% 
      hchart(., "line", 
             hcaes(x = date, y = settle, group = cmdty)) %>% 
      #hc_colors(cols) %>%
      hc_tooltip(valueDecimals = 2) %>% 
      hc_xAxis(title = list(text = "Data")) %>% 
      hc_yAxis(title = list(text = "Settle"))

```

---
## Série de Retornos

```{r Grafico2 - Retornos}

cmdty_raw %>% 
      mutate(daily_return = daily_return*100) %>% 
      hchart(., "line", 
             hcaes(x = date, y = daily_return, group = cmdty)) %>% 
      #hc_colors(cols) %>%
      hc_tooltip(valueDecimals = 2) %>% 
      hc_xAxis(title = list(text = "Data")) %>% 
      hc_yAxis(title = list(text = "Retorno Diário"),
               labels = list(format = "{value}%"))

```

---
## Volatilidade

```{r}

cmdty_raw %>% 
      mutate(sq_return = sq_return*100) %>% 
      hchart(., "line", 
             hcaes(x = date, y = sq_return, group = cmdty)) %>% 
      #hc_colors(cols) %>%
      hc_tooltip(valueDecimals = 2) %>% 
      hc_xAxis(title = list(text = "Data")) %>% 
      hc_yAxis(title = list(text = "Proxy da Volatilidade"),
               labels = list(format = "{value}%"))

```

